DROP TABLE IF EXISTS usuarios;
DROP TABLE IF EXISTS vertederos;

CREATE TABLE usuario (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE vertederos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    usuario_id INTEGER NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tipo TEXT NOT NULL,
    descripcion TEXT NOT NULL,
    foto TEXT
);
